name: Trivy Scan

on:
  workflow_dispatch:

jobs:
  security:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      
      - name: Run Trivy (console output)
        uses: aquasecurity/trivy-action@df678dbccf677bc6937338d569ba0da18964a8cc
        with:
          scan-type: 'fs'
          format: 'table'
          severity: 'HIGH,CRITICAL'
          exit-code: '0'
      
      - name: Run Trivy (sarif)
        uses: aquasecurity/trivy-action@df678dbccf677bc6937338d569ba0da18964a8cc
        with:
          scan-type: 'fs'
          format: 'sarif'
          severity: 'HIGH,CRITICAL'
          exit-code: '0'
          output: 'trivy-results.sarif'
      
      - name: Upload to GitHub Security
        uses: github/codeql-action/upload-sarif@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'
